//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sites")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub endpoint: Option<String>,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_ids::Entity",
        from = "Column::UserId",
        to = "super::user_ids::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserIds,
}

impl Related<super::user_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserIds.def()
    }
}
